<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>PHP Quizzer</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="public/style.css">
    </head>
    <body>
        <header>
            <div class="container">
                <h1>PHP Quizzer</h1>
            </div>
        </header> 
        <main>
            <div class="container">
                    <h2>You're Done!</h2>
                    <p>Congrats! You have completed the test!</p>
                    <p>Final Score: <?= $_SESSION['score']?></p>
                    <a href="/" class="start">Take Again</a>
            </div>
        </main>
        <footer>
            <div class="container">
                Copyright &copy 2019, PHP Quizzer
            </div>
        </footer>
    </body>
</html>