<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>PHP Quizzer</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="public/style.css?v=<?php echo time(); ?>">
    </head>
    <body>
        <header>
            <div class="container">
                <h1>PHP Quizzer</h1>
            </div>
        </header> 
        <main>
            <div class="container">
                <h2>Test your PHP Knowlegde</h2>
                <p>This is a multiple choice quiz to test your knowledge of PHP</p>
            <ul>
                <li><strong>Number of questions: </strong><?= $total?></li>
                <li><strong>Type: </strong>Multiple Choice</li>
                <li><strong>Estimated time: </strong> <?= $total * 0.5?> Minutes</li>
            </ul>
            <a href="/start-quiz?n=1" class="start">Start Quiz</a>
            <a href="/admin" class="admin">Admin</a>
            </div>
        </main>
        <footer>
            <div class="container">
                Copyright &copy 2019, PHP Quizzer
            </div>
        </footer>
    </body>
</html>